name: Build

on:
  push:
    branches: [ ios-jb ]
  pull_request:
    branches: [ ios-jb ]

jobs:
  build-njb:
    runs-on: macos-13
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install build utilities
      run: |
        sudo xcode-select -s /Applications/Xcode_13.1.app/Contents/Developer
        brew install ninja bartycrouch dpkg s3cmd libmagic dos2unix
        /Applications/Xcode_13.1.app/Contents/Developer/usr/bin/python3 -m pip install polib python-magic
        
    - name: Create Keychain
      run: |
        security create-keychain -p alpine build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p alpine build.keychain
        security set-keychain-settings -t 36000 build.keychain
        security import "Source/iOS/DolphiniOS/Common/Build Resources/OatmealDomeSoftware.p12" -k build.keychain -P ${{ secrets.CERTIFICATE_GPG_PASSWORD }} -A
        security set-key-partition-list -S apple-tool:,apple: -s -k alpine build.keychain
        
    - name: Prepare Resources
      run: |
        cd Source/iOS/DolphiniOS/DolphiniOS
        gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.FIREBASE_GPG_PASSWORD }}" --output GoogleService-Info.plist GoogleService-Info.plist.gpg
        /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $((${{ github.run_number }} - 1))" Info.plist
        cd "../Common/Bundle Resources"
        rm SpecialThanks.txt
        wget -O SpecialThanks.txt https://smash.oatmealdome.me/parts/patrons.txt
        dos2unix SpecialThanks.txt
    
    - name: Cache CocoaPods
      uses: actions/cache@v1
      with:
        path: Source/iOS/DolphiniOS/Pods
        key: ${{ runner.OS }}-pods-cache-${{ hashFiles('**/Source/iOS/DolphiniOS/Podfile.lock') }}
    
    - name: Run CocoaPods
      run: |
        cd Source/iOS/DolphiniOS
        pod install
      
    - name: Build
      env:
        XCODEBUILD_ARGS: "BUILD_DIR=${{ github.workspace }}/build-Xcode GCC_PREPROCESSOR_DEFINITIONS='$GCC_PREPROCESSOR_DEFINITIONS ANALYTICS=1' CODE_SIGNING_ALLOWED=\"NO\" CODE_SIGNING_REQUIRED=\"NO\" CODE_SIGN_ENTITLEMENTS=\"\" CODE_SIGN_IDENTITY=\"\"" 
      run: |
        mkdir build-Xcode
        cd Source/iOS/DolphiniOS
        xcodebuild -workspace DolphiniOS.xcworkspace -configuration "Release (Non-Jailbroken)" -scheme "DolphiniOS" ${{ env.XCODEBUILD_ARGS }}
        xcodebuild -workspace DolphiniOS.xcworkspace -configuration "Release (Patreon Non-Jailbroken)" -scheme "DolphiniOS" ${{ env.XCODEBUILD_ARGS }}    
        
    - name: Package (Normal)
      env:
        PROJECT_DIR: "${{ github.workspace }}/Source/iOS/DolphiniOS"
        ARCHIVE_PATH: "${{ github.workspace }}/build-Xcode/archive-root-njb"
        BUILD_FOR_PATREON: "NO"
        IS_CI: "YES"
      run: |
        mkdir -p ${{ env.ARCHIVE_PATH }}/Products/Applications/
        cp -R "${{ github.workspace }}/build-Xcode/Release (Non-Jailbroken)-iphoneos/DolphiniOS.app" ${{ env.ARCHIVE_PATH }}/Products/Applications/
        "Source/iOS/DolphiniOS/Common/Build Resources/Scripts/BuildIpa.sh" build.keychain NJB_IPA_PATH
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: DolphiniOS-NJB.ipa
        path: ${{ env.NJB_IPA_PATH }}/DolphiniOS-NJB.ipa
